

services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=azar.inesuribe.es
      - LETSENCRYPT_HOST=azar.inesuribe.es
      - LETSENCRYPT_EMAIL=email@inesuribe.es
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true

# services:
#   nginx:
#     image: nginx:latest
#     expose:
#       - "80"
#     environment:
#       - VIRTUAL_HOST=azar.inesuribe.es,www.azar.inesuribe.es
#       - LETSENCRYPT_HOST=azar.inesuribe.es,www.azar.inesuribe.es
#       - LETSENCRYPT_EMAIL=email@inesuribe.es
#     volumes:
#       - ./web:/usr/share/nginx/html:ro
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#     networks:
#       - proxy
#     restart: unless-stopped

#   backend:
#     build: ./backend
#     expose:
#       - "3001"
#     environment:
#       - VIRTUAL_HOST=api.azar.inesuribe.es
#       - LETSENCRYPT_HOST=api.azar.inesuribe.es  
#       - LETSENCRYPT_EMAIL=email@inesuribe.es
#       - BASE_URL=https://azar.inesuribe.es
#     env_file:
#       - ./backend/.env 
#     volumes:
#       - ./backend:/app
#     networks:
#       - proxy
#     restart: unless-stopped

# networks:
#   proxy:
#     name: nginx-proxy
#     external: true