export const foundationTranslations = {
    es: {
        visionTitle: 'Nuestra Visión',
        visionText: 'En Fundación Azar queremos reflexionar alrededor del significado del término «arte» dentro del panorama cultural contemporáneo. Nos gusta creer que las obras nacen tanto de la creatividad de los artistas, como del <em>savoir-faire</em> de los artesanos o la mecánica de los pensadores. Y también nos gusta imaginar que uno de los caminos para reformular la creación es facilitando el encuentro fortuito entre distintas disciplinas fomentando el diálogo y la «polinización cruzada».<br /><br />Por ello deseamos, a través de un programa de residencias, publicaciones, obras colaborativas y eventos culturales, invitar a artistas, artesanos y pensadores a compartir, desarrollar y nutrir nuestras inquietudes sobre el proceso creativo.',
        
        teamTitle: 'Nuestro Equipo',
        knowUs: 'Descubre la historia detrás de cada miembro',

            paulaName: 'Paula G. Gener',
            paulaRole: 'Directora',
            paulaBio: 'Paula, nacida en Bilbao, dirige el programa de Fundación Azar con el fin de contribuir al desarrollo y consolidación de las iniciativas y trayectorias de artistas, artesanos y pensadores.<br/><br/>Comenzó su camino acádemico en IE University, donde cursó una doble licenciatura en Administración de Empresas y Derecho en inglés, con la intención de aplicar sus conocimientos a proyectos dentro del ámbito cultural. Durante este periodo, también trabajó en desarrollo de negocio para la startup InovRetail y accedió a University of British Columbia, Canadá, donde realizó formaciones en cine y fotografía. Su interés por representar a artistas de manera justa e informada, le llevó a formarse como abogada de propiedad intelectual, realizando un doble máster de Acceso a la Abogacía y Propiedad Intelectual y Nuevas Tecnologías en ESADE. <br/><br/>Tras un periodo en el prestigioso despacho de abogados Cuatrecasas, Paula se mudó a Londres para especializarse en comisariado, gestión de negocios artísticos, historia del arte y arte contemporáneo en Sotheby’s Institute of Art. Posteriormente, trabajó en Galería Pedro Cera durante su apertura en Madrid. <br/><br/>Paralelamente, su interés y devoción por las artes y el panorama cultural contemporáneo le ha llevado a realizar otros proyectos como la promoción del sello discográfico independiente Quinoa Records y la edición y publicación de su primer relato de fotografía analógica <em>La señal prometida (2024)</em>.',
            paulaQuote: "",
        
            nathalieName: 'Nathalie Trafford',
            nathalieRole: 'Presidenta y co-fundadora',
            nathalieBio: 'Nathalie Trafford nace en Santiago de Chile en 1966. Crece en Madrid y descubre el medio del cine trabajando como asistente de arte en los años ochenta, cuando España se abría al mundo. Después de su bachillerato, se marcha a París a estudiar Historia del Arte en la Sorbona y, paralelamente, explora los oficios del cine en rodajes franceses y españoles. En 1996, en Francia, funda Paraíso Production Diffusion con el propósito de descubrir y acompañar a directores de cine audaces y singulares, creando puentes entre culturas y países.<br/><br/>Hasta hoy ha producido veinte largometrajes y más de treinta cortometrajes. Entre sus últimas películas destacan El empleado y el patrón de Manuel Nieto (Quinzaine des Réalisateurs Cannes 2021), Nueve Sevillas de Pedro G. Romero y Gonzalo García Pelayo (Premio a la mejor película en el Festival de Sevilla, Nuevas Olas, 2020), Con el viento de Meritxell Colell, presentado en 2018 en la Berlinale, y Belle Dormant de Ado Arrietta, seleccionado en Rotterdam en 2017 y nominado al premio Louis Delluc. Acaba de terminar En la alcoba del sultán de Javier Rebollo, que se estrenará en octubre de 2024 en la Seminci de Valladolid.<br/><br/>Esta será su última película como productora de cine, ya que planea dedicarse plenamente a la Fundación Azar.',
            nathalieQuote: "Cuando empecé a fantasear con una residencia artística, me pareció una extensión natural de mi trabajo como productora. ‘Estar río arriba’ es mi espacio geográfico preferido. Por el momento, esta residencia es solo una idea, pero me gustaría que se convirtiera en un flujo, una narrativa, como en el cine, de modo que, con los años y las ediciones, cuente una historia singular y rigurosa. También me gustaría que reuniera a pensadores, soñadores, artistas, artesanos, creadores e inventores… Y quizás, de las chispas que surgirán de estos encuentros, la obra de arte emergerá aquí o… en otro lugar.",

            denisName: 'Denis Curty',
            denisRole: 'Co-fundador',
            denisBio: 'Denis Curty, nacido en París, ha trabajado durante más de cuarenta años como director de escena y director técnico en una amplia variedad de eventos culturales, entre ellos el festival Montpellier Danse, el festival Paris Quartier d’Été y en importantes teatros parisinos como Le Châtelet y el Théâtre de la Ville (ahora Théâtre Sarah Bernhardt). A lo largo de su carrera, ha colaborado con algunos de los más grandes artistas de la escena internacional, como Bob Wilson, Robert Carsen, Trisha Brown, Dominique Bagouet, Pina Bausch, Bouvier Obadia y Thomas Ostermeier.<br/><br/>También ha desarrollado una segunda carrera en el mundo de los museos, desempeñándose como director técnico de exposiciones, talleres y programas para el público joven en el Centro Pompidou y el Museo de Arte Moderno de la Ville de Paris.<br/><br/>Desde 2024, es el director técnico del evento La Nuit Blanche en París.<br/><br/>Toda esta vasta experiencia en el vibrante entorno cultural francés ha despertado en él el deseo de poner sus conocimientos al servicio de un proyecto personal: Fundación Azar, en España, un país que ama profundamente y que sigue descubriendo.',
            denisQuote: "",

            clickThis: "Haz click!",
        
    },
    en: {
        visionTitle: 'Our Vision',
        visionText: 'At Fundación Azar, we want to reflect on the meaning of the term «art» within the contemporary cultural landscape. We like to believe that works are born not only from the creativity of artists but also from the <em>savoir-faire</em> of artisans and the mechanics of thinkers. We also like to imagine that one of the ways to rethink creation is by facilitating the fortuitous encounter between different disciplines, fostering dialogue and «cross-pollination».<br /><br />For this reason, through a program of residencies, publications, collaborative works, and cultural events, we wish to invite artists, artisans, and thinkers to share, develop, and nurture our concerns about the creative process.',
        
        teamTitle: 'Our Team',
        knowUs: 'Discover the story behind each member',

            paulaName: 'Paula G. Gener',
            paulaRole: 'Director',
            paulaBio: "Paula, born in Bilbao, directs the Azar Foundation program, which aims to contribute to the development and consolidation of the initiatives and careers of artists, artisans, and thinkers. <br/><br/>She began her academic career at IE University, where she pursued a double degree in Business Administration and Law in English, with the intention of applying her knowledge to projects within the cultural field. During this period, she also worked in business development for the startup InovRetail and gained admission to the University of British Columbia, Canada, where she studied film and photography. Her interest in representing artists in a fair and informed manner led her to train as an intellectual property lawyer, completing a double master's degree in Access to the Bar and Intellectual Property and New Technologies at ESADE.<br/><br/>After a period at the prestigious law firm Cuatrecasas, Paula moved to London to specialize in curating, art business management, art history, and contemporary art at Sotheby's Institute of Art. She subsequently worked at Galería Pedro Cera during its opening in Madrid.<br/><br/>At the same time, his interest and devotion to the arts and the contemporary cultural scene has led him to carry out other projects such as the promotion of the independent record label Quinoa Records and the editing and publication of his first analog photography story <em>The Promised Signal (2024)</em>.",
            paulaQuote: "",

            nathalieName: 'Nathalie Trafford',
            nathalieRole: 'President and co-founder',
            nathalieBio: "Nathalie Trafford was born in Santiago, Chile, in 1966. She grew up in Madrid and discovered the medium of film while working as an art assistant in the 1980s, as Spain opened up to the world. After high school, she went to Paris to study art history at the Sorbonne and, at the same time, explored the craft of filmmaking on French and Spanish sets. In 1996, in France, she founded Paraíso Production Diffusion with the aim of discovering and supporting bold and unique filmmakers, building bridges between cultures and countries.<br/><br/>To date, he has produced twenty feature films and more than thirty short films. His  most recent films include El vendedor y el patrón  by Manuel Nieto (Cannes Directors' Quinzaine 2021),  Nueve Sevillas  by Pedro G. Romero and Gonzalo García Pelayo (Best Film Award at the Seville Film Festival, Nuevas Olas, 2020),  Con el viento  by Meritxell Colell, presented at the Berlinale in 2018, and  Belle Dormant  by Ado Arrietta, selected for Rotterdam in 2017 and nominated for the Louis Delluc Award. He has just completed  En la alcoba del sultán  by Javier Rebollo, which will premiere in October 2024 at the Seminci in Valladolid.<br/><br/>This will be her last film as a film producer, as she plans to dedicate herself fully to the Azar Foundation.",
            nathalieQuote: "When I started fantasizing about an artist residency, it seemed like a natural extension of my work as a producer. 'Being upstream' is my favorite geographic space. For now, this residency is just an idea, but I would like it to become a flow, a narrative, like in cinema, so that, over the years and with editions, it tells a singular and rigorous story. I would also like it to bring together thinkers, dreamers, artists, artisans, creators, and inventors… And perhaps, from the sparks that will arise from these encounters, the work of art will emerge here or… elsewhere.",

            denisName: 'Denis Curty',
            denisRole: 'Co-founder',
            denisBio: "Born in Paris, Denis Curty has worked for over forty years as a stage manager and technical director for a wide variety of cultural events, including the Montpellier Danse Festival, the Paris Quartier d'Été Festival, and major Parisian theaters such as Le Châtelet and the Théâtre de la Ville (now Théâtre Sarah Bernhardt). Throughout his career, he has collaborated with some of the greatest artists on the international stage, including Bob Wilson, Robert Carsen, Trisha Brown, Dominique Bagouet, Pina Bausch, Bouvier Obadia, and Thomas Ostermeier.<br/><br/>He has also developed a second career in the museum world, serving as technical director of exhibitions, workshops, and programs for young audiences at the Centre Pompidou and the Musée d'Art Moderne de la Ville de Paris. <br/><br/>Since 2024, he has been the technical director of the La Nuit Blanche event in Paris.<br/><br/>All this vast experience in the vibrant French cultural environment has awakened in him the desire to put his knowledge to work for a personal project: the Azar Foundation, in Spain, a country he deeply loves and continues to explore.",
            denisQuote: "",

            clickThis: "Click here!",

    },
    pt: {
        visionTitle: 'Nossa Visão',
        visionText: 'Na Fundação Azar, queremos refletir sobre o significado do termo «arte» dentro do panorama cultural contemporâneo. Gostamos de acreditar que as obras nascem tanto da criatividade dos artistas quanto do <em>savoir-faire</em> dos artesãos e da mecânica dos pensadores. Também gostamos de imaginar que uma das formas de reformular a criação é facilitando o encontro fortuito entre diferentes disciplinas, promovendo o diálogo e a «polinização cruzada».<br /><br />Por isso, por meio de um programa de residências, publicações, obras colaborativas e eventos culturais, desejamos convidar artistas, artesãos e pensadores a compartilhar, desenvolver e nutrir nossas inquietações sobre o processo criativo.',
        
        teamTitle: 'Nossa Equipe',
        knowUs: 'Descubra a história por trás de cada membro',

            paulaName: 'Paula G. Gener',
            paulaRole: 'Diretora',
            paulaBio: 'Paula, nascida em Bilbao, dirige o programa da Fundação Azar com o objetivo de contribuir para o desenvolvimento e consolidação das iniciativas e trajetórias de artistas, artesãos e pensadores.<br/><br/>Iniciou seu percurso acadêmico na IE University, onde cursou uma dupla graduação em Administração de Empresas e Direito em inglês, com a intenção de aplicar seus conhecimentos a projetos na área cultural. Durante esse período, também trabalhou no desenvolvimento de negócios para a startup InovRetail e foi aceita na University of British Columbia, no Canadá, onde realizou formações em cinema e fotografia. Seu interesse em representar artistas de forma justa e informada a levou a se formar como advogada de propriedade intelectual, realizando um duplo mestrado em Acesso à Advocacia e Propriedade Intelectual e Novas Tecnologias na ESADE.<br/><br/>Após um período no prestigiado escritório de advocacia Cuatrecasas, Paula mudou-se para Londres para se especializar em curadoria, gestão de negócios artísticos, história da arte e arte contemporânea no Sotheby’s Institute of Art. Posteriormente, trabalhou na Galería Pedro Cera durante sua abertura em Madrid.<br/><br/>Paralelamente, seu interesse e devoção pelas artes e pelo panorama cultural contemporâneo a levaram a realizar outros projetos, como a promoção do selo discográfico independente Quinoa Records e a edição e publicação de seu primeiro relato de fotografia analógica, <em>O Sinal Prometido (2024)</em>.',
            paulaQuote: "",

            nathalieName: 'Nathalie Trafford',
            nathalieRole: 'Presidente e cofundadora',
            nathalieBio: 'Nathalie Trafford nasceu em Santiago do Chile em 1966. Cresceu em Madrid e descobriu o meio cinematográfico trabalhando como assistente de arte nos anos oitenta, quando a Espanha se abria ao mundo. Após o ensino médio, mudou-se para Paris para estudar História da Arte na Sorbonne e, paralelamente, explorou os ofícios do cinema em filmagens francesas e espanholas. Em 1996, na França, fundou a Paraíso Production Diffusion com o propósito de descobrir e acompanhar diretores de cinema audaciosos e singulares, criando pontes entre culturas e países.<br/><br/>Até hoje, produziu vinte longas-metragens e mais de trinta curtas-metragens. Entre seus últimos filmes destacam-se El empleado y el patrón, de Manuel Nieto (Quinzaine des Réalisateurs Cannes 2021), Nueve Sevillas, de Pedro G. Romero e Gonzalo García Pelayo (Prêmio de Melhor Filme no Festival de Sevilha, Nuevas Olas, 2020), Con el viento, de Meritxell Colell, apresentado em 2018 na Berlinale, e Belle Dormant, de Ado Arrietta, selecionado em Rotterdam em 2017 e indicado ao prêmio Louis Delluc. Acaba de finalizar En la alcoba del sultán, de Javier Rebollo, que estreará em outubro de 2024 na Seminci de Valladolid.<br/><br/>Este será seu último filme como produtora, pois planeja se dedicar plenamente à Fundação Azar.',
            nathalieQuote: "Quando comecei a sonhar com uma residência artística, pareceu-me uma extensão natural do meu trabalho como produtora. ‘Estar rio acima’ é o meu espaço geográfico preferido. Por enquanto, esta residência é apenas uma ideia, mas gostaria que se tornasse um fluxo, uma narrativa, como no cinema, de modo que, ao longo dos anos e das edições, conte uma história singular e rigorosa. Também gostaria que reunisse pensadores, sonhadores, artistas, artesãos, criadores e inventores… E talvez, das faíscas que surgirão desses encontros, a obra de arte emerja aqui ou… em outro lugar.",
            
            denisName: 'Denis Curty',
            denisRole: 'Cofundador',
            denisBio: 'Denis Curty, nascido em Paris, trabalhou durante mais de quarenta anos como diretor de cena e diretor técnico em uma ampla variedade de eventos culturais, entre eles o festival Montpellier Danse, o festival Paris Quartier d’Été e importantes teatros parisienses como Le Châtelet e o Théâtre de la Ville (atualmente Théâtre Sarah Bernhardt). Ao longo de sua carreira, colaborou com alguns dos maiores artistas da cena internacional, como Bob Wilson, Robert Carsen, Trisha Brown, Dominique Bagouet, Pina Bausch, Bouvier Obadia e Thomas Ostermeier.<br/><br/>Também desenvolveu uma segunda carreira no mundo dos museus, atuando como diretor técnico de exposições, oficinas e programas para o público jovem no Centro Pompidou e no Museu de Arte Moderna da Ville de Paris.<br/><br/>Desde 2024, é diretor técnico do evento La Nuit Blanche em Paris.<br/><br/>Toda essa vasta experiência no vibrante ambiente cultural francês despertou nele o desejo de colocar seus conhecimentos a serviço de um projeto pessoal: a Fundação Azar, na Espanha, um país que ama profundamente e continua descobrindo.',
            denisQuote: "",

            clickThis: "Clique!",
    }
};
